sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbweight;'
  - git clone https://github.com/hold12/CDIO_final_sql
  - mysql -u root dbweight < CDIO_final_sql/tables.sql
  - mysql -u root dbweight < CDIO_final_sql/views/operator.sql
  - sudo apt-get install ant-optional

notifications:
  email:
    recipiens:
      - anders@wiberg.tech
    on_success: never
    on_failure: change