sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - git clone https://github.com/hold12/CDIO_final_sql
  - mysql -u root testdb < CDIO_final_sql/tables.sql

notifications:
  email:
    recipiens:
      - anders@wiberg.tech
    on_success: never
    on_failure: change